### PR TITLE
GEODE-9334: Update UG generation scripts

### PR DESCRIPTION
**Pull request by alb3rtobr**
This PR aligns the user guide generation instructions and scripts with the instructions recently added in Geode (see GEODE-9042).

Uplifts Bookbinder and other gems version, and simplifies the Docker-based scripts to preview the user guides.

### CODE REVIEW

**Review by davebarnes97 — APPROVED** [review]
LGTM

**Review by moleske — APPROVED** [review]
Woo hoo!

**Comment by alb3rtobr** [comment]
CI fails but not due to this PR content.
Clang-format failing saying I should format a file I have not modified. And the "build-windows-2016-vs-2017-debug" failed due to the worker machine has not "tar" installed 😮.

**Comment by pdxcodemonkey** [comment]
I'm attempting to address CI issues - today is day 2 :/.  PR #819 has the formatting fix in it - we updated the version of `clang-format` to 12 the other day because that's the new default for homebrew on MacOS, and now we have one file already checked into `develop` that it doesn't like.  LGTM is also failing right now because of errors downloading ACE.  Please stand by, we'll get it sorted ASAP.

**Comment by alb3rtobr** [comment]
thanks for the info @pdxcodemonkey . BTW I saw the clang uplift so I installed clang 12. If I run `cmake --build . --target all-clangformat` there are two files that are modified, but `RegionAttributes.cpp` is not one of them:

`cppcache/include/geode/CacheableString.hpp`
`cppcache/integration/framework/Cluster.cpp`

**Comment by pdxcodemonkey** [comment]
Still working on that, as well.  We're slowly coming to the conclusion that not only is `clang-format` subtly incompatible between versions, it is also sometimes subtly incompatible in _the same version_ between platforms, most notably Windows.  In this case, however, I think we've accidentally picked up a daily build version or something, because if you run the CI Docker image it reports this:

```
root@87ac1e844af6:/# clang-format --version
Ubuntu clang-format version 12.0.1-++20210525082622+328a6ec95532-1~exp1~20210525063352.95
```
Again, we're working on it.  Multiple fires to put out right now :)

**Comment by pdxcodemonkey** [comment]
@alb3rtobr please rebase onto latest `develop` to fix `clang-format, then this will pass gates and can be merged.

**Comment by alb3rtobr** [comment]
> @alb3rtobr please rebase onto latest `develop` to fix `clang-format, then this will pass gates and can be merged.

done, thanks!

**Pull request merged**
