### PR TITLE
GEODE-8227: Updates CMake to 3.16.8.

### PR DESCRIPTION
**Pull request by pivotal-jbarrett**

### CODE REVIEW

**Comment by moleske** [comment]
Is this to update the minimum required version also?  Or just to get packer things updated?  The Jira issue doesn't go into detail

**Comment by pivotal-jbarrett** [comment]
> Is this to update the minimum required version also? Or just to get packer things updated? The Jira issue doesn't go into detail

Little of both... The current images have a really old CMake. There are some ACE removal branches that need newer CMake.

**Comment by moleske** [comment]
> Little of both... The current images have a really old CMake. There are some ACE removal branches that need newer CMake.

Thanks for the information.  My request would be to update https://github.com/apache/geode-native/blob/develop/CMakeLists.txt#L16 to new required version of cmake

**Comment by pivotal-jbarrett** [comment]
> Thanks for the information. My request would be to update https://github.com/apache/geode-native/blob/develop/CMakeLists.txt#L16 to new required version of cmake

Chicken and egg problem. If you make that change in this PR the CI fails because the images aren't updated with the new version of CMake. Technically our CMake files are currently compatible with older versions of CMake. Though that will change soon.

**Comment by moleske** [comment]
> Chicken and egg problem. If you make that change in this PR the CI fails because the images aren't updated with the new version of CMake. Technically our CMake files are currently compatible with older versions of CMake. Though that will change soon.

No problem 😄 Just want to make sure stuff comes to eventual consistency

**Pull request merged**
