### PR TITLE
GEODE-7697: OpenSSL 1.1.0 minimum required, removed openssl-compat

### PR DESCRIPTION
**Pull request by mreddington**

### CODE REVIEW

**Comment by mreddington** [comment]
I've updated the minimum version to 1.1.1.

**Comment by pivotal-jbarrett** [comment]
Despite that fact that people shouldn't be using OpenSSL 1.1.0 or less, is there a compelling reason to remove support for it?

**Comment by mreddington** [comment]
Yes, the OpenSSL documentation is explicit that it is not thread safe, and we see a host of runtime bugs because of it. Forcing a minimum version fixes them and reduces the amount of code we have to maintain for backwards compatibility that never actually worked.

**Comment by pivotal-jbarrett** [comment]
> Yes, the OpenSSL documentation is explicit that it is not thread safe, and we see a host of runtime bugs because of it. Forcing a minimum version fixes them and reduces the amount of code we have to maintain for backwards compatibility that never actually worked.

For clarity, what is not thread safe? The whole of OpenSSL prior to 1.1.1?

**Comment by pdxcodemonkey** [comment]
We've merged the SSL code into the client proper, so this is no longer relevant.

**Pull request closed without merging**
