### PR TITLE
GEODE-8676: Update Bookbindery

### PR DESCRIPTION
**Pull request by moleske**
Bump bookbindery from 10.1.14 to 10.1.15 in /docs/geode-native-book-cpp
Bump bookbindery from 10.1.14 to 10.1.15 in /docs/geode-native-book-dotnet

Bump to newer ruby so it works

Authored-by: M. Oleske <michael@oleske.engineer>

I was playing around with [dependabot](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically) on my [own repo](https://github.com/moleske/geode-native/pull/20) and it pointed out this was out of date.  Sometime in the future it would be nice to automate this but there's some things I'm trying to figure out before that.  This bump required a newer ruby version so that's why the dockerfile got updated.

Tested this by hand and it seemed alright, but certainly should get some eyes on it.

Also this should fix some security alerts I've been getting for other out of date components brought in

### CODE REVIEW

**Comment by moleske** [comment]
close and open to trigger travis (failed due to unable to pull docker image, maybe related to docker hub rate limits?)

**Comment by moleske** [comment]
hmm...I think `view-docs.sh` is not quite working.  Not sure why though 🤷‍♀️.  Will see what @davebarnes97 thinks

**Comment by davebarnes97** [comment]
@moleske I, too, get errors when executing the view-docs.sh script, whether specifyinng 'cpp' or 'dotnet'.
The problem is a mismatch between ruby versions. I've never fully understood how this works, but one improvement that at least produces a clearer error message is to prefix the `rackup` command with `bundle exec`, which then at least takes into account the Gemfile.lock in the final_app directory which was just generated by the preceding `bundle install` command.
So as a first step toward better behavior, I recommend modifying this line in view-docs.sh:

```
-  /bin/bash -c "bundle install; rackup --host 0.0.0.0 -p ${PORT}"
+  /bin/bash -c "bundle install; bundle exec rackup --host 0.0.0.0 -p ${PORT}"
```

The error report is then much simpler than the long walkback:
```
$ ./view-docs.sh cpp
Building geode-native/docsbuild:0.1 image...
sha256:67c86b19096df731ba1d48a60bd75688bdda24ec4ad66d3d438386865cdf00fc
Building geode-native/docsbuild:0.1-dbarnes image...
sha256:227d9fae7dad6ba2d2876505ed567844763854bef962114f0eb362634423b5d0
Starting up web server...
Your Ruby version is 2.4.10, but your Gemfile specified ~> 2.5.0
Your Ruby version is 2.4.10, but your Gemfile specified ~> 2.5.0
```

**Comment by moleske** [comment]
bumped it again, but ran into some other problems.  Hoping your ruby knowledge helps

**Comment by davebarnes97** [comment]
> bumped it again, but ran into some other problems. Hoping your ruby knowledge helps

My ruby knowledge -- that's a good one.
Tell you what, though, this version of the PR worked for me. Ship it!

**Review by davebarnes97 — APPROVED** [review]
Worked for me!

**Pull request merged**
