### PR TITLE
GEODE-2763: Remove of nonSingleHopsCount stat in client

### PR DESCRIPTION
**Pull request by ameybarve15**
GEODE-2763: Remove of nonSingleHopsCount stat in client from 
1. source 
2. cpp and csharp unit tests and
3. documentation.

Ran unit tests and integration-tests

### CODE REVIEW

**Comment by echobravopapa** [comment]
@ameybarve15 would you please squash your commits, TIA

**Comment by ameybarve15** [comment]
@echobravopapa I am following https://cwiki.apache.org/confluence/display/GEODE/Code+contributions
I can squash commits post pull request is approved.

**Comment by echobravopapa** [comment]
@ameybarve15 @PivotalSarge will have a look at this soon.  
May we stay on the feature branch until the PR is approved, which will alleviate the  "merge" commit...

**Comment by ameybarve15** [comment]
Hi @echobravopapa , and @PivotalSarge Thanks for your review.
I am trying to merge my pull request but get this error.

>~/source/open/t/geode-native (develop) $ git fetch ameyGitHub pull/90/head:feature/GEODE-2763
fatal: Couldn't find remote ref pull/90/head

Please help me resolve the issue.

**Comment by pivotal-jbarrett** [comment]
You shouldn't merge develop into your feature branch. You should rebase your feature branch on develop. This creates a much cleaner merge of the feature back into develop when approved.

**Comment by ameybarve15** [comment]
Ok, but for this branch I have already merged develop, Let me know If you can merge this request in this state or else I will create a new branch again and follow the entire procedure again

**Comment by echobravopapa** [comment]
@ameybarve15 it is simpler to start with a fresh feature branch and follow what @pivotal-jbarrett suggests

**Pull request closed without merging**
