### PR TITLE
GEODE-7620: Updates CMake to properly include macOS SDK.

### PR DESCRIPTION
**Pull request by pivotal-jbarrett**
* Upgrades 3rd party dependencies.

### CODE REVIEW

**Comment by pivotal-jbarrett** [comment]
> let's please back out the boost update until we get a version that builds properly. I don't remember the context, but I did have to skip a prior update for the same reason.

Can you provide more context on "builds properly"?

**Comment by pdxcodemonkey** [comment]
Have you looked at the Travis output?

**Comment by pivotal-jbarrett** [comment]
> Have you looked at the Travis output?

Oh, the clang analyzer failure. On it.

**Comment by pivotal-jbarrett** [comment]
Hold on this PR until #567 is resolved.

**Pull request merged**
