### PR TITLE
Add rat checks to travis-ci build

### PR DESCRIPTION
**Pull request by metatype**

### CODE REVIEW

**Comment by PivotalSarge** [comment]
Where is .ratignore? I don't see it.

**Comment by echobravopapa** [comment]
@PivotalSarge .ratignore is in the base dir of geode-native

**Comment by PivotalSarge** [comment]
Ah. `find` does not behave like I think it does with respect to finding dot files in the current directory.

**Comment by echobravopapa** [comment]
I quoted the target, suspecting find would not like it otherwise...

**Pull request closed without merging**
