### PR TITLE
GEODE-3143 : close socket before deteting

### PR DESCRIPTION
**Pull request by fdaniel7**
Closing socket before deleting it.

### CODE REVIEW

**Comment by pivotal-jbarrett** [comment]
It looks like your reverts were to undo changes to .gitignore. I'd suggest not building from within the source tree at all. If you do there is an ignore already for "build" that you can use as your build directory. CMake promotes building outside the source directory, you can generate your project files from any location.

**Comment by fdaniel7** [comment]
Hi I'm still new with github, it is indeed a small change. On next contributions I'll pay more attention.

**Comment by echobravopapa** [comment]
@fdaniel7  What is the GEODE ticket you are working on?

**Comment by fdaniel7** [comment]
There's no ticket for this as far as I know. I'm fixing this as part of reviewing geode client code

**Comment by pivotal-jbarrett** [comment]
Please open a JIRA and include it in your commit message.

GEODE-1234: blah blah

**Comment by fdaniel7** [comment]
When connect() is invoked from one of TcpConn::TcpConn the TcpConn object is not created since the exception is thrown from the constructor, so ~TcpConn will not be invoked.

**Comment by echobravopapa** [comment]
@fdaniel7 please close this PR, thx

**Pull request closed without merging**
