### PR TITLE
GEODE-9189: Upgrades dependencies. 

### PR DESCRIPTION
**Pull request by pivotal-jbarrett**
Upgrades Boost to 1.76.
Upgrades ACE to 7.0.1.
Upgrades SQLite to 3.35.5
Upgrades GTest to follow head.
Upgrades Benchmark to follow head.
Fixes Xerces-C to use Apache mirrors.

### CODE REVIEW

**Comment by moleske** [comment]
If you're like me and were curious why gtest is following head now instead of a release, gtest now follows [live-at-head philosophy](https://abseil.io/about/philosophy#upgrade-support)

**Comment by pivotal-jbarrett** [comment]
> If you're like me and were curious why gtest is following head now instead of a release, gtest now follows [live-at-head philosophy](https://abseil.io/about/philosophy#upgrade-support)

Google Benchmark also started following the same philosophy but didn't really let anymore know.

**Comment by mmartell** [comment]
I strongly agree with Abseil's "Live at Head" philiosophy, which appears to be largely adopted by Google's 250 million lines of C++.

**Review by mmartell — APPROVED** [review]
Looks good to me. Especially like that nothing breaks.

**Comment by pivotal-jbarrett** [comment]
Converted this back to draft again. There is one issue I want to resolve. CMake with either always update the git based projects on every compile or never unless forced by invoking the update target directly. I want to find a middle ground like a time based invocation, like no more than every 24h, similar to how Maven snapshots are updated.

**Review by mreddington — APPROVED** [review]

**Pull request closed without merging**
