### PR TITLE
Revert "GEODE-8991: Implement cached region clean up (#757)"

### PR DESCRIPTION
**Pull request by pdxcodemonkey**
- Consistent failures in legacy C++ test testThinClientHADistOps in CI

This reverts commit 33c960d6dce07a3dc04f9ed6d020ce35d2033c79.

### CODE REVIEW

**Comment by gaussianrecurrence** [comment]
Sorry this made an old IT fail. Not sure why this did not pop up before in CI. I am looking at why the test is failing. Once solved, I'll create a new PR for GEODE-8991

**Comment by pdxcodemonkey** [comment]
After a little debugging on Windows, we see the code throwing from this block

{code}
  if (bytes_read == 0) {
    auto elapsedTime = std::chrono::duration<double, std::micro>(
        std::chrono::system_clock::now() - beforeReadPoint);
    if (elapsedTime < timeout) {
      LOGDEBUG("Throwing an IO exception");
      socket_.cancel();
      // Get the abort
      io_context_.restart();
      io_context_.run();
      throw boost::system::system_error{boost::asio::error::broken_pipe};
    }
{code}
in TcpConn::receive_nothrowiftimeout.  Here's the callstack:

pivotal-gemfire.dll!apache::geode::client::TcpConn::receive(char * buff, unsigned __int64 len, std::chrono::duration<__int64,std::ratio<1,1000> > timeout, bool throwTimeoutException) Line 233
	at c:\users\bblake\src\geode-native\cppcache\src\tcpconn.cpp(233)
pivotal-gemfire.dll!apache::geode::client::TcpConn::receive(char * buff, unsigned __int64 len, std::chrono::duration<__int64,std::ratio<1,1000> > timeout) Line 186
	at c:\users\bblake\src\geode-native\cppcache\src\tcpconn.cpp(186)
pivotal-gemfire.dll!apache::geode::client::TcrConnection::receiveData(char * buffer, unsigned __int64 length, std::chrono::duration<__int64,std::ratio<1,1000000> > timeout) Line 495
	at c:\users\bblake\src\geode-native\cppcache\src\tcrconnection.cpp(495)
pivotal-gemfire.dll!apache::geode::client::TcrConnection::readMessage(unsigned __int64 * recvLen, std::chrono::duration<__int64,std::ratio<1,1000000> > receiveTimeoutSec, bool doHeaderTimeoutRetries, apache::geode::client::ConnErrType * opErr, bool isNotificationMessage, int request) Line 650
	at c:\users\bblake\src\geode-native\cppcache\src\tcrconnection.cpp(650)
pivotal-gemfire.dll!apache::geode::client::TcrConnection::receive(unsigned __int64 * recvLen, apache::geode::client::ConnErrType * opErr, std::chrono::duration<__int64,std::ratio<1,1000000> > receiveTimeoutSec) Line 634
	at c:\users\bblake\src\geode-native\cppcache\src\tcrconnection.cpp(634)
pivotal-gemfire.dll!apache::geode::client::TcrEndpoint::receiveNotification(std::atomic<bool> & isRunning) Line 556
	at c:\users\bblake\src\geode-native\cppcache\src\tcrendpoint.cpp(556)
pivotal-gemfire.dll!apache::geode::client::Task<apache::geode::client::TcrEndpoint>::svc() Line 79
	at c:\users\bblake\src\geode-native\cppcache\src\task.hpp(79)
pivotal-gemfire.dll!std::_Invoker_pmf_pointer::_Call<void (__cdecl apache::geode::client::Task<apache::geode::client::TcrEndpoint>::*)(void),apache::geode::client::Task<apache::geode::client::TcrEndpoint> *>(void(apache::geode::client::Task<apache::geode::client::TcrEndpoint>::*)() _Pmf, apache::geode::client::Task<apache::geode::client::TcrEndpoint> * && _Arg1)
pivotal-gemfire.dll!std::invoke<void (__cdecl apache::geode::client::Task<apache::geode::client::TcrEndpoint>::*)(void),apache::geode::client::Task<apache::geode::client::TcrEndpoint> *>(void(apache::geode::client::Task<apache::geode::client::TcrEndpoint>::*)() && _Obj, apache::geode::client::Task<apache::geode::client::TcrEndpoint> * && <_Args_0>)
pivotal-gemfire.dll!std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl apache::geode::client::Task<apache::geode::client::TcrEndpoint>::*)(void),apache::geode::client::Task<apache::geode::client::TcrEndpoint> *>,std::default_delete<std::tuple<void (__cdecl apache::geode::client::Task<apache::geode::client::TcrEndpoint>::*)(void),apache::geode::client::Task<apache::geode::client::TcrEndpoint> *> > > >::_Execute<0,1>(std::tuple<void (__cdecl apache::geode::client::Task<apache::geode::client::TcrEndpoint>::*)(void),apache::geode::client::Task<apache::geode::client::TcrEndpoint> *> & _Tup, std::integer_sequence<unsigned __int64,0,1> __formal) Line 239
	at c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\thr\xthread(239)
pivotal-gemfire.dll!std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl apache::geode::client::Task<apache::geode::client::TcrEndpoint>::*)(void),apache::geode::client::Task<apache::geode::client::TcrEndpoint> *>,std::default_delete<std::tuple<void (__cdecl apache::geode::client::Task<apache::geode::client::TcrEndpoint>::*)(void),apache::geode::client::Task<apache::geode::client::TcrEndpoint> *> > > >::_Run(std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl apache::geode::client::Task<apache::geode::client::TcrEndpoint>::*)(void),apache::geode::client::Task<apache::geode::client::TcrEndpoint> *>,std::default_delete<std::tuple<void (__cdecl apache::geode::client::Task<apache::geode::client::TcrEndpoint>::*)(void),apache::geode::client::Task<apache::geode::client::TcrEndpoint> *> > > > * _Ln) Line 245
	at c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\thr\xthread(245)
pivotal-gemfire.dll!std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl apache::geode::client::Task<apache::geode::client::TcrEndpoint>::*)(void),apache::geode::client::Task<apache::geode::client::TcrEndpoint> *>,std::default_delete<std::tuple<void (__cdecl apache::geode::client::Task<apache::geode::client::TcrEndpoint>::*)(void),apache::geode::client::Task<apache::geode::client::TcrEndpoint> *> > > >::_Go() Line 231
	at c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\thr\xthread(231)
pivotal-gemfire.dll!std::_Pad::_Call_func(void * _Data) Line 209
	at c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\thr\xthread(209)

**Review by echobravopapa — APPROVED** [review]

**Review by mmartell — APPROVED** [review]
Agree, just create a new PR when this gets figured out.

**Comment by gaussianrecurrence** [comment]
As it seems the issue was the test failing was registering interest for some specific keys which at cleanup time did not exist. And the function was throwing an exception because of that. I already have a fix for it. But I'd prefer to have the commit reverted and make the new PR adding some additional ITs to cover these cases.

**Pull request merged**
