### PR TITLE
GEODE-7235: Disable a couple of new Clang warnings temporarily

### PR DESCRIPTION
**Pull request by pdxcodemonkey**
- Got a new version of the compiler from Apple, this is breaking Mac builds

### CODE REVIEW

**Comment by pdxcodemonkey** [comment]
@mreddington @steve-sienk @vfordpivotal @charliemblack @dihardman

**Comment by pdxcodemonkey** [comment]
Filed GEODE-7326 to track the actual fix.

**Comment by pivotal-jbarrett** [comment]
@pdxcodemonkey 
I wish I would have been able to jump on this sooner. Matching based on the OS doesn't seem appropriate for something that is compiler specific. You should be matching compiler. Better yet, you should probably be using `check_cxx_compiler_flag(<flag> <var>)` to test that the version of the compiler in question even has the flags you are going to be passing to it. Since this is a temporary fix I am not going to get caught up on it. Please make sure the fix JIRA references these commits so that they can be backed out later.

**Comment by pdxcodemonkey** [comment]
That's interesting - think I may have seen this feature in cmake and forgotten about it.  Hard to tell, given the ridiculous # of features available in cmake, but anyway this is clearly the right way to go.  I guess it's good in the sense that this will give me a strong incentive to get the code fix in place and back this out ASAP.

**Pull request merged**
