### PR TITLE
GEODE-9322: Fix possible race condition on new ITs

### PR DESCRIPTION
**Pull request by gaussianrecurrence**
- Solved a potential race condition in TransactionCleaningTest TS
   due to the fact that no checks were performed after starting/stopping
   the server.

### CODE REVIEW

**Comment by gaussianrecurrence** [comment]
If @pdxcodemonkey @pivotal-jbarrett @mreddington @alb3rtobr @mkevo @mivanac @jvarenina could take a look at this, I'd appreciate it quite much!

Also note that PR #806 depends on this PR, given the fixed IT fails pretty frequently.

**Review by pdxcodemonkey — APPROVED** [review]
Looks good - though I don't fully understand the nature of the race condition you mention, I trust you've been over the details and fixed.

Quick question - this part of your description: "Modified RegisterKeysTest to use gmock_actions helper."  I see no changes to RegisterKeysTest.  Are they missing, or is your PR description just out of date?

**Comment by gaussianrecurrence** [comment]
> Looks good - though I don't fully understand the nature of the race condition you mention, I trust you've been over the details and fixed.

Regarding this, basically it solves race condition in which the test proceeds before the server is actually stopped. Note that gfsh command "stop server" is not synchronous, so after its execution the server could be still up.

> Quick question - this part of your description: "Modified RegisterKeysTest to use gmock_actions helper." I see no changes to RegisterKeysTest. Are they missing, or is your PR description just out of date?

Thanks for noticing this. As it seems to me, I made this fix along with PR #809, so in order to make the changes work there was some duplicity on both PRs, as #809 was merged I guess the delta doesn't show the RegisterKeysTest anymore. I'll update the description.

Just a comment: I would like to improve the readability for the code in general and ITs in particular. So do you think it is possible to add a comment on ITs with a short description of what it does, as well as what's the test for?

**Comment by pdxcodemonkey** [comment]
I agree it'd probably be a great idea to document the tests intent in Doxygen comments or similar.  Perhaps bring this up on the dev list or just file a JIRA ticket.  I don't think we wish to bother with the "old" tests, but for sure everything in the new suite should be properly understood.

**Pull request merged**
