### PR TITLE
GEODE-9036: Fix FixedPartitionAttributes coredump

### PR DESCRIPTION
**Pull request by gaussianrecurrence**
- Fixed coredump whenever instantiating FixedPartitionAttributesImpl.
 - Also, small changes to fix Clang 11 compilation for this file.
 - Added an UT to verify the coredump does not happens.

### CODE REVIEW

**Review by mkevo — APPROVED** [review]
Nice work!

**Review by pdxcodemonkey — APPROVED** [review]
:facepalm:  Thanks for fixing our dumb bug.

**Comment by pdxcodemonkey** [comment]
@gaussianrecurrence Please rebase onto the latest develop to pick up the fix for the test that's failing, then I can merge/close (failing CI now blocks merging).

**Comment by gaussianrecurrence** [comment]
> @gaussianrecurrence Please rebase onto the latest develop to pick up the fix for the test that's failing, then I can merge/close (failing CI now blocks merging).

Done!

**Pull request merged**
